# Generated by Django 3.1.4 on 2022-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotable',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
